"""add governorate continuous monitoring

Revision ID: 09c5a23259ef
Revises: 1b81d508fc86
Create Date: 2026-09-22 02:01:42.307138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c5a23259ef'
down_revision: Union[str, None] = '1b81d508fc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governorate_monitoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('governorate_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governorate_monitoring_governorate_id'), 'governorate_monitoring', ['governorate_id'], unique=True)
    op.create_index(op.f('ix_governorate_monitoring_id'), 'governorate_monitoring', ['id'], unique=False)
    op.create_index(op.f('ix_governorate_monitoring_is_active'), 'governorate_monitoring', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governorate_monitoring_is_active'), table_name='governorate_monitoring')
    op.drop_index(op.f('ix_governorate_monitoring_id'), table_name='governorate_monitoring')
    op.drop_index(op.f('ix_governorate_monitoring_governorate_id'), table_name='governorate_monitoring')
    op.drop_table('governorate_monitoring')
    # ### end Alembic commands ###
